name: my_project
version: '1.0'
profile: my_project  # profiles.yml のターゲット名
model-paths: ["models"]

# dbtをUbuntu上で実行しており、そちら(\\wsl$\Ubuntu\home\username\.dbt)にprofiles.ymlを置いている(そっちでinitした)ため、
# dbt1005: No profiles.yml found at pathが出力される
# おいたらおいたでこっちを優先して見たうえでJWTが有効でないとか言ってくるため放置
# mountしてUbuntu上で実行する分には支障ない